/**
 * UNDERCOVER - Words Database
 * Base de données des paires de mots (500+ paires)
 */

export const WORD_PAIRS = [
  // ==================== NOURRITURE ====================
  { main: 'Pizza', similar: 'Tarte' },
  { main: 'Croissant', similar: 'Pain au chocolat' },
  { main: 'Hamburger', similar: 'Sandwich' },
  { main: 'Sushi', similar: 'Maki' },
  { main: 'Glace', similar: 'Sorbet' },
  { main: 'Café', similar: 'Thé' },
  { main: 'Bière', similar: 'Cidre' },
  { main: 'Champagne', similar: 'Vin pétillant' },
  { main: 'Pâtes', similar: 'Riz' },
  { main: 'Fromage', similar: 'Yaourt' },
  { main: 'Pomme', similar: 'Poire' },
  { main: 'Banane', similar: 'Plantain' },
  { main: 'Chocolat', similar: 'Caramel' },
  { main: 'Gâteau', similar: 'Muffin' },
  { main: 'Bonbon', similar: 'Chewing-gum' },
  { main: 'Coca-Cola', similar: 'Pepsi' },
  { main: 'Jus d\'orange', similar: 'Limonade' },
  { main: 'Crêpe', similar: 'Gaufre' },
  { main: 'Soupe', similar: 'Ragoût' },
  { main: 'Salade', similar: 'Crudités' },
  { main: 'Steak', similar: 'Côtelette' },
  { main: 'Poulet rôti', similar: 'Dinde' },
  { main: 'Frites', similar: 'Potatoes' },
  { main: 'Omelette', similar: 'Œufs brouillés' },
  { main: 'Tartine', similar: 'Toast' },
  { main: 'Confiture', similar: 'Miel' },
  { main: 'Beurre', similar: 'Margarine' },
  { main: 'Lait', similar: 'Crème' },
  { main: 'Pain', similar: 'Baguette' },
  { main: 'Brioche', similar: 'Pain de mie' },
  { main: 'Chips', similar: 'Crackers' },
  { main: 'Popcorn', similar: 'Cacahuètes' },
  { main: 'Olive', similar: 'Câpre' },
  { main: 'Cornichon', similar: 'Pickles' },
  { main: 'Ketchup', similar: 'Mayonnaise' },
  { main: 'Moutarde', similar: 'Wasabi' },
  { main: 'Sel', similar: 'Poivre' },
  { main: 'Sucre', similar: 'Édulcorant' },
  { main: 'Vinaigre', similar: 'Citron' },
  { main: 'Huile d\'olive', similar: 'Huile de tournesol' },
  { main: 'Spaghetti', similar: 'Nouilles' },
  { main: 'Lasagne', similar: 'Cannelloni' },
  { main: 'Ravioli', similar: 'Tortellini' },
  { main: 'Couscous', similar: 'Semoule' },
  { main: 'Quinoa', similar: 'Boulgour' },
  { main: 'Tomate', similar: 'Poivron' },
  { main: 'Carotte', similar: 'Navet' },
  { main: 'Oignon', similar: 'Échalote' },
  { main: 'Ail', similar: 'Gingembre' },
  { main: 'Aubergine', similar: 'Courgette' },
  
  // ==================== ANIMAUX ====================
  { main: 'Chien', similar: 'Loup' },
  { main: 'Chat', similar: 'Tigre' },
  { main: 'Cheval', similar: 'Âne' },
  { main: 'Vache', similar: 'Taureau' },
  { main: 'Mouton', similar: 'Chèvre' },
  { main: 'Poule', similar: 'Coq' },
  { main: 'Canard', similar: 'Oie' },
  { main: 'Lapin', similar: 'Lièvre' },
  { main: 'Souris', similar: 'Rat' },
  { main: 'Abeille', similar: 'Guêpe' },
  { main: 'Papillon', similar: 'Libellule' },
  { main: 'Aigle', similar: 'Faucon' },
  { main: 'Dauphin', similar: 'Marsouin' },
  { main: 'Baleine', similar: 'Orque' },
  { main: 'Crocodile', similar: 'Alligator' },
  { main: 'Serpent', similar: 'Anguille' },
  { main: 'Tortue', similar: 'Escargot' },
  { main: 'Grenouille', similar: 'Crapaud' },
  { main: 'Requin', similar: 'Espadon' },
  { main: 'Thon', similar: 'Saumon' },
  { main: 'Sardine', similar: 'Anchois' },
  { main: 'Crevette', similar: 'Langoustine' },
  { main: 'Homard', similar: 'Crabe' },
  { main: 'Moule', similar: 'Huître' },
  { main: 'Pieuvre', similar: 'Calamar' },
  { main: 'Méduse', similar: 'Anémone' },
  { main: 'Étoile de mer', similar: 'Oursin' },
  { main: 'Lion', similar: 'Tigre' },
  { main: 'Léopard', similar: 'Guépard' },
  { main: 'Ours', similar: 'Panda' },
  { main: 'Éléphant', similar: 'Rhinocéros' },
  { main: 'Girafe', similar: 'Okapi' },
  { main: 'Zèbre', similar: 'Cheval' },
  { main: 'Hippopotame', similar: 'Phoque' },
  { main: 'Gorille', similar: 'Chimpanzé' },
  { main: 'Singe', similar: 'Babouin' },
  { main: 'Kangourou', similar: 'Wallaby' },
  { main: 'Koala', similar: 'Paresseux' },
  { main: 'Pingouin', similar: 'Manchot' },
  { main: 'Autruche', similar: 'Émeu' },
  { main: 'Flamant rose', similar: 'Cigogne' },
  { main: 'Perroquet', similar: 'Pie' },
  { main: 'Corbeau', similar: 'Corneille' },
  { main: 'Moineau', similar: 'Pigeon' },
  { main: 'Hirondelle', similar: 'Martinet' },
  { main: 'Hibou', similar: 'Chouette' },
  { main: 'Chauve-souris', similar: 'Vampire' },
  { main: 'Renard', similar: 'Coyote' },
  { main: 'Loup', similar: 'Chacal' },
  { main: 'Écureuil', similar: 'Tamia' },
  { main: 'Castor', similar: 'Loutre' },
  { main: 'Hérisson', similar: 'Porc-épic' },
  { main: 'Taupe', similar: 'Musaraigne' },
  { main: 'Blaireau', similar: 'Raton laveur' },
  { main: 'Cerf', similar: 'Chevreuil' },
  { main: 'Sanglier', similar: 'Cochon' },
  { main: 'Chameau', similar: 'Dromadaire' },
  { main: 'Lama', similar: 'Alpaga' },
  { main: 'Morse', similar: 'Otarie' },
  { main: 'Phoque', similar: 'Lion de mer' },
  { main: 'Fourmi', similar: 'Termite' },
  { main: 'Coccinelle', similar: 'Scarabée' },
  { main: 'Mouche', similar: 'Moustique' },
  { main: 'Araignée', similar: 'Scorpion' },
  { main: 'Chenille', similar: 'Ver de terre' },
  { main: 'Sauterelle', similar: 'Criquet' },
  { main: 'Cigale', similar: 'Grillon' },
  
  // ==================== LIEUX ====================
  { main: 'Plage', similar: 'Piscine' },
  { main: 'Montagne', similar: 'Colline' },
  { main: 'Forêt', similar: 'Jungle' },
  { main: 'Désert', similar: 'Savane' },
  { main: 'Restaurant', similar: 'Café' },
  { main: 'Cinéma', similar: 'Théâtre' },
  { main: 'Hôpital', similar: 'Clinique' },
  { main: 'École', similar: 'Université' },
  { main: 'Église', similar: 'Mosquée' },
  { main: 'Stade', similar: 'Gymnase' },
  { main: 'Aéroport', similar: 'Gare' },
  { main: 'Hôtel', similar: 'Auberge' },
  { main: 'Musée', similar: 'Galerie' },
  { main: 'Bibliothèque', similar: 'Librairie' },
  { main: 'Prison', similar: 'Caserne' },
  { main: 'Zoo', similar: 'Aquarium' },
  { main: 'Parc', similar: 'Jardin' },
  { main: 'Ferme', similar: 'Ranch' },
  { main: 'Usine', similar: 'Entrepôt' },
  { main: 'Bureau', similar: 'Open space' },
  { main: 'Supermarché', similar: 'Épicerie' },
  { main: 'Boulangerie', similar: 'Pâtisserie' },
  { main: 'Pharmacie', similar: 'Parapharmacie' },
  { main: 'Banque', similar: 'Poste' },
  { main: 'Casino', similar: 'Discothèque' },
  { main: 'Bar', similar: 'Pub' },
  { main: 'Spa', similar: 'Sauna' },
  { main: 'Coiffeur', similar: 'Barbier' },
  { main: 'Garage', similar: 'Atelier' },
  { main: 'Chantier', similar: 'Carrière' },
  { main: 'Port', similar: 'Marina' },
  { main: 'Phare', similar: 'Tour' },
  { main: 'Château', similar: 'Palais' },
  { main: 'Grotte', similar: 'Caverne' },
  { main: 'Volcan', similar: 'Geyser' },
  { main: 'Cascade', similar: 'Fontaine' },
  { main: 'Île', similar: 'Atoll' },
  { main: 'Glacier', similar: 'Banquise' },
  { main: 'Canyon', similar: 'Gorge' },
  { main: 'Marais', similar: 'Marécage' },
  { main: 'Oasis', similar: 'Palmeraie' },
  { main: 'Pyramide', similar: 'Temple' },
  { main: 'Cimetière', similar: 'Mausolée' },
  { main: 'Ambassade', similar: 'Consulat' },
  { main: 'Tribunal', similar: 'Mairie' },
  { main: 'Commissariat', similar: 'Gendarmerie' },
  { main: 'Crèche', similar: 'Garderie' },
  { main: 'Maternité', similar: 'Clinique' },
  { main: 'Laboratoire', similar: 'Centre de recherche' },
  { main: 'Observatoire', similar: 'Planétarium' },
  
  // ==================== TRANSPORT ====================
  { main: 'Voiture', similar: 'Camionnette' },
  { main: 'Moto', similar: 'Scooter' },
  { main: 'Vélo', similar: 'Trottinette' },
  { main: 'Train', similar: 'Métro' },
  { main: 'Avion', similar: 'Hélicoptère' },
  { main: 'Bateau', similar: 'Ferry' },
  { main: 'Bus', similar: 'Tramway' },
  { main: 'Taxi', similar: 'VTC' },
  { main: 'Camion', similar: 'Fourgon' },
  { main: 'Ambulance', similar: 'Pompiers' },
  { main: 'Fusée', similar: 'Navette' },
  { main: 'Sous-marin', similar: 'Bathyscaphe' },
  { main: 'Paquebot', similar: 'Croisière' },
  { main: 'Voilier', similar: 'Catamaran' },
  { main: 'Yacht', similar: 'Jet-ski' },
  { main: 'Canoë', similar: 'Kayak' },
  { main: 'Planche à voile', similar: 'Kitesurf' },
  { main: 'Montgolfière', similar: 'Dirigeable' },
  { main: 'Parapente', similar: 'Deltaplane' },
  { main: 'Téléphérique', similar: 'Funiculaire' },
  { main: 'TGV', similar: 'Eurostar' },
  { main: 'Quad', similar: 'Buggy' },
  { main: 'Tracteur', similar: 'Moissonneuse' },
  { main: 'Bulldozer', similar: 'Pelleteuse' },
  { main: 'Grue', similar: 'Chariot élévateur' },
  { main: 'Skateboard', similar: 'Longboard' },
  { main: 'Roller', similar: 'Patin à glace' },
  { main: 'Luge', similar: 'Bobsleigh' },
  { main: 'Motoneige', similar: 'Ski-doo' },
  { main: 'Segway', similar: 'Hoverboard' },
  
  // ==================== OBJETS DU QUOTIDIEN ====================
  { main: 'Téléphone', similar: 'Tablette' },
  { main: 'Ordinateur', similar: 'Laptop' },
  { main: 'Télévision', similar: 'Écran' },
  { main: 'Montre', similar: 'Horloge' },
  { main: 'Lunettes', similar: 'Lentilles' },
  { main: 'Parapluie', similar: 'Parasol' },
  { main: 'Couteau', similar: 'Ciseaux' },
  { main: 'Fourchette', similar: 'Cuillère' },
  { main: 'Chaise', similar: 'Tabouret' },
  { main: 'Table', similar: 'Bureau' },
  { main: 'Lit', similar: 'Canapé' },
  { main: 'Lampe', similar: 'Bougie' },
  { main: 'Miroir', similar: 'Vitre' },
  { main: 'Porte', similar: 'Fenêtre' },
  { main: 'Clé', similar: 'Cadenas' },
  { main: 'Sac à dos', similar: 'Valise' },
  { main: 'Portefeuille', similar: 'Porte-monnaie' },
  { main: 'Réveil', similar: 'Minuteur' },
  { main: 'Calculatrice', similar: 'Abaque' },
  { main: 'Stylo', similar: 'Crayon' },
  { main: 'Cahier', similar: 'Carnet' },
  { main: 'Livre', similar: 'Magazine' },
  { main: 'Journal', similar: 'Gazette' },
  { main: 'Enveloppe', similar: 'Colis' },
  { main: 'Timbre', similar: 'Autocollant' },
  { main: 'Agrafeuse', similar: 'Perforatrice' },
  { main: 'Classeur', similar: 'Pochette' },
  { main: 'Gomme', similar: 'Correcteur' },
  { main: 'Règle', similar: 'Équerre' },
  { main: 'Compas', similar: 'Rapporteur' },
  { main: 'Brosse à dents', similar: 'Fil dentaire' },
  { main: 'Savon', similar: 'Gel douche' },
  { main: 'Shampoing', similar: 'Après-shampoing' },
  { main: 'Rasoir', similar: 'Tondeuse' },
  { main: 'Sèche-cheveux', similar: 'Lisseur' },
  { main: 'Peigne', similar: 'Brosse' },
  { main: 'Serviette', similar: 'Peignoir' },
  { main: 'Oreiller', similar: 'Coussin' },
  { main: 'Couette', similar: 'Couverture' },
  { main: 'Drap', similar: 'Housse' },
  { main: 'Rideau', similar: 'Store' },
  { main: 'Tapis', similar: 'Moquette' },
  { main: 'Aspirateur', similar: 'Balai' },
  { main: 'Fer à repasser', similar: 'Défroisseur' },
  { main: 'Machine à laver', similar: 'Sèche-linge' },
  { main: 'Lave-vaisselle', similar: 'Évier' },
  { main: 'Four', similar: 'Micro-ondes' },
  { main: 'Réfrigérateur', similar: 'Congélateur' },
  { main: 'Grille-pain', similar: 'Toaster' },
  { main: 'Cafetière', similar: 'Bouilloire' },
  { main: 'Mixeur', similar: 'Blender' },
  { main: 'Robot culinaire', similar: 'Batteur' },
  { main: 'Poêle', similar: 'Casserole' },
  { main: 'Wok', similar: 'Sauteuse' },
  { main: 'Cocotte', similar: 'Marmite' },
  { main: 'Passoire', similar: 'Égouttoir' },
  { main: 'Râpe', similar: 'Mandoline' },
  { main: 'Ouvre-boîte', similar: 'Tire-bouchon' },
  { main: 'Planche à découper', similar: 'Billot' },
  { main: 'Rouleau à pâtisserie', similar: 'Moule' },
  { main: 'Fouet', similar: 'Spatule' },
  { main: 'Louche', similar: 'Écumoire' },
  
  // ==================== VÊTEMENTS ====================
  { main: 'T-shirt', similar: 'Polo' },
  { main: 'Jean', similar: 'Pantalon' },
  { main: 'Robe', similar: 'Jupe' },
  { main: 'Veste', similar: 'Manteau' },
  { main: 'Chaussures', similar: 'Baskets' },
  { main: 'Chapeau', similar: 'Casquette' },
  { main: 'Écharpe', similar: 'Foulard' },
  { main: 'Gants', similar: 'Moufles' },
  { main: 'Chaussettes', similar: 'Collants' },
  { main: 'Maillot de bain', similar: 'Bikini' },
  { main: 'Pyjama', similar: 'Chemise de nuit' },
  { main: 'Pull', similar: 'Sweat' },
  { main: 'Chemise', similar: 'Blouse' },
  { main: 'Cravate', similar: 'Nœud papillon' },
  { main: 'Ceinture', similar: 'Bretelles' },
  { main: 'Blouson', similar: 'Parka' },
  { main: 'Imperméable', similar: 'Ciré' },
  { main: 'Doudoune', similar: 'Anorak' },
  { main: 'Costume', similar: 'Smoking' },
  { main: 'Jogging', similar: 'Survêtement' },
  { main: 'Short', similar: 'Bermuda' },
  { main: 'Legging', similar: 'Caleçon' },
  { main: 'Slip', similar: 'Boxer' },
  { main: 'Soutien-gorge', similar: 'Brassière' },
  { main: 'Sandales', similar: 'Tongs' },
  { main: 'Bottes', similar: 'Bottines' },
  { main: 'Escarpins', similar: 'Talons' },
  { main: 'Mocassins', similar: 'Loafers' },
  { main: 'Béret', similar: 'Bonnet' },
  { main: 'Bandana', similar: 'Turban' },
  { main: 'Lunettes de soleil', similar: 'Masque de ski' },
  { main: 'Montre', similar: 'Bracelet' },
  { main: 'Collier', similar: 'Pendentif' },
  { main: 'Boucles d\'oreilles', similar: 'Créoles' },
  { main: 'Bague', similar: 'Alliance' },
  
  // ==================== SPORTS ====================
  { main: 'Football', similar: 'Rugby' },
  { main: 'Basketball', similar: 'Handball' },
  { main: 'Tennis', similar: 'Badminton' },
  { main: 'Natation', similar: 'Plongée' },
  { main: 'Boxe', similar: 'Karaté' },
  { main: 'Ski', similar: 'Snowboard' },
  { main: 'Golf', similar: 'Mini-golf' },
  { main: 'Course', similar: 'Marathon' },
  { main: 'Cyclisme', similar: 'VTT' },
  { main: 'Escalade', similar: 'Alpinisme' },
  { main: 'Surf', similar: 'Bodyboard' },
  { main: 'Judo', similar: 'Aikido' },
  { main: 'Taekwondo', similar: 'Kung-fu' },
  { main: 'Escrime', similar: 'Kendo' },
  { main: 'Tir à l\'arc', similar: 'Arbalète' },
  { main: 'Équitation', similar: 'Polo' },
  { main: 'Patinage', similar: 'Hockey' },
  { main: 'Gymnastique', similar: 'Acrobatie' },
  { main: 'Athlétisme', similar: 'Décathlon' },
  { main: 'Aviron', similar: 'Canoë' },
  { main: 'Voile', similar: 'Planche à voile' },
  { main: 'Triathlon', similar: 'Biathlon' },
  { main: 'Cricket', similar: 'Baseball' },
  { main: 'Volleyball', similar: 'Beach-volley' },
  { main: 'Ping-pong', similar: 'Squash' },
  { main: 'Billard', similar: 'Snooker' },
  { main: 'Bowling', similar: 'Pétanque' },
  { main: 'Fléchettes', similar: 'Tir' },
  { main: 'Musculation', similar: 'CrossFit' },
  { main: 'Yoga', similar: 'Pilates' },
  { main: 'Danse', similar: 'Ballet' },
  { main: 'Parkour', similar: 'Freerun' },
  { main: 'Skateboard', similar: 'BMX' },
  { main: 'Parachutisme', similar: 'Base jump' },
  { main: 'Rafting', similar: 'Canyoning' },
  
  // ==================== MÉTIERS ====================
  { main: 'Médecin', similar: 'Infirmier' },
  { main: 'Avocat', similar: 'Juge' },
  { main: 'Professeur', similar: 'Formateur' },
  { main: 'Policier', similar: 'Gendarme' },
  { main: 'Pompier', similar: 'Secouriste' },
  { main: 'Chef cuisinier', similar: 'Pâtissier' },
  { main: 'Architecte', similar: 'Ingénieur' },
  { main: 'Acteur', similar: 'Comédien' },
  { main: 'Chanteur', similar: 'Musicien' },
  { main: 'Photographe', similar: 'Vidéaste' },
  { main: 'Journaliste', similar: 'Reporter' },
  { main: 'Écrivain', similar: 'Romancier' },
  { main: 'Peintre', similar: 'Sculpteur' },
  { main: 'Designer', similar: 'Graphiste' },
  { main: 'Développeur', similar: 'Programmeur' },
  { main: 'Chirurgien', similar: 'Anesthésiste' },
  { main: 'Dentiste', similar: 'Orthodontiste' },
  { main: 'Vétérinaire', similar: 'Zoologiste' },
  { main: 'Pharmacien', similar: 'Biologiste' },
  { main: 'Comptable', similar: 'Auditeur' },
  { main: 'Banquier', similar: 'Trader' },
  { main: 'Notaire', similar: 'Huissier' },
  { main: 'Plombier', similar: 'Électricien' },
  { main: 'Menuisier', similar: 'Ébéniste' },
  { main: 'Maçon', similar: 'Carreleur' },
  { main: 'Couturier', similar: 'Tailleur' },
  { main: 'Coiffeur', similar: 'Esthéticienne' },
  { main: 'Boulanger', similar: 'Meunier' },
  { main: 'Boucher', similar: 'Charcutier' },
  { main: 'Poissonnier', similar: 'Ostréiculteur' },
  { main: 'Agriculteur', similar: 'Éleveur' },
  { main: 'Jardinier', similar: 'Paysagiste' },
  { main: 'Fleuriste', similar: 'Horticulteur' },
  { main: 'Pilote', similar: 'Copilote' },
  { main: 'Steward', similar: 'Hôtesse' },
  { main: 'Capitaine', similar: 'Marin' },
  { main: 'Chauffeur', similar: 'Livreur' },
  { main: 'Mécanicien', similar: 'Garagiste' },
  { main: 'Serveur', similar: 'Barman' },
  { main: 'Réceptionniste', similar: 'Concierge' },
  { main: 'Guide', similar: 'Accompagnateur' },
  { main: 'Agent immobilier', similar: 'Promoteur' },
  { main: 'Psychologue', similar: 'Psychiatre' },
  { main: 'Sage-femme', similar: 'Obstétricien' },
  { main: 'Kinésithérapeute', similar: 'Ostéopathe' },
  { main: 'Diététicien', similar: 'Nutritionniste' },
  { main: 'Coach', similar: 'Mentor' },
  { main: 'Arbitre', similar: 'Entraîneur' },
  { main: 'Scientifique', similar: 'Chercheur' },
  { main: 'Astronaute', similar: 'Cosmonaute' },
  
  // ==================== MUSIQUE ====================
  { main: 'Guitare', similar: 'Basse' },
  { main: 'Piano', similar: 'Synthétiseur' },
  { main: 'Batterie', similar: 'Percussion' },
  { main: 'Violon', similar: 'Alto' },
  { main: 'Flûte', similar: 'Clarinette' },
  { main: 'Trompette', similar: 'Trombone' },
  { main: 'Saxophone', similar: 'Hautbois' },
  { main: 'Harpe', similar: 'Lyre' },
  { main: 'Accordéon', similar: 'Bandonéon' },
  { main: 'Harmonica', similar: 'Kazoo' },
  { main: 'Djembé', similar: 'Bongo' },
  { main: 'Xylophone', similar: 'Marimba' },
  { main: 'Contrebasse', similar: 'Violoncelle' },
  { main: 'Mandoline', similar: 'Banjo' },
  { main: 'Ukulélé', similar: 'Guitare' },
  { main: 'Orgue', similar: 'Clavecin' },
  { main: 'Rock', similar: 'Metal' },
  { main: 'Pop', similar: 'Variété' },
  { main: 'Jazz', similar: 'Blues' },
  { main: 'Rap', similar: 'Hip-hop' },
  { main: 'Reggae', similar: 'Ska' },
  { main: 'Techno', similar: 'House' },
  { main: 'Classique', similar: 'Baroque' },
  { main: 'Country', similar: 'Folk' },
  { main: 'Salsa', similar: 'Bachata' },
  { main: 'Tango', similar: 'Valse' },
  { main: 'Opéra', similar: 'Comédie musicale' },
  { main: 'Gospel', similar: 'Soul' },
  { main: 'Funk', similar: 'Disco' },
  { main: 'Grunge', similar: 'Punk' },
  
  // ==================== NATURE ====================
  { main: 'Soleil', similar: 'Lune' },
  { main: 'Étoile', similar: 'Planète' },
  { main: 'Nuage', similar: 'Brouillard' },
  { main: 'Pluie', similar: 'Neige' },
  { main: 'Rivière', similar: 'Ruisseau' },
  { main: 'Lac', similar: 'Étang' },
  { main: 'Océan', similar: 'Mer' },
  { main: 'Arbre', similar: 'Arbuste' },
  { main: 'Fleur', similar: 'Plante' },
  { main: 'Herbe', similar: 'Mousse' },
  { main: 'Rocher', similar: 'Caillou' },
  { main: 'Sable', similar: 'Gravier' },
  { main: 'Terre', similar: 'Argile' },
  { main: 'Boue', similar: 'Marécage' },
  { main: 'Arc-en-ciel', similar: 'Aurore boréale' },
  { main: 'Éclair', similar: 'Tonnerre' },
  { main: 'Ouragan', similar: 'Tornade' },
  { main: 'Tsunami', similar: 'Raz-de-marée' },
  { main: 'Tremblement de terre', similar: 'Séisme' },
  { main: 'Éruption', similar: 'Explosion' },
  { main: 'Chêne', similar: 'Hêtre' },
  { main: 'Sapin', similar: 'Épicéa' },
  { main: 'Palmier', similar: 'Cocotier' },
  { main: 'Bambou', similar: 'Roseau' },
  { main: 'Rose', similar: 'Tulipe' },
  { main: 'Marguerite', similar: 'Pâquerette' },
  { main: 'Tournesol', similar: 'Dahlia' },
  { main: 'Orchidée', similar: 'Lys' },
  { main: 'Lavande', similar: 'Romarin' },
  { main: 'Menthe', similar: 'Basilic' },
  { main: 'Cactus', similar: 'Aloès' },
  { main: 'Fougère', similar: 'Lierre' },
  { main: 'Champignon', similar: 'Truffe' },
  { main: 'Mousse', similar: 'Lichen' },
  { main: 'Algue', similar: 'Corail' },
  
  // ==================== TECHNOLOGIES ====================
  { main: 'Facebook', similar: 'Instagram' },
  { main: 'WhatsApp', similar: 'Telegram' },
  { main: 'Netflix', similar: 'Disney+' },
  { main: 'Google', similar: 'Bing' },
  { main: 'Amazon', similar: 'eBay' },
  { main: 'iPhone', similar: 'Samsung' },
  { main: 'Windows', similar: 'MacOS' },
  { main: 'WiFi', similar: 'Bluetooth' },
  { main: 'YouTube', similar: 'TikTok' },
  { main: 'Twitter', similar: 'Threads' },
  { main: 'LinkedIn', similar: 'Viadeo' },
  { main: 'Snapchat', similar: 'BeReal' },
  { main: 'Spotify', similar: 'Deezer' },
  { main: 'Uber', similar: 'Bolt' },
  { main: 'Airbnb', similar: 'Booking' },
  { main: 'PayPal', similar: 'Stripe' },
  { main: 'Bitcoin', similar: 'Ethereum' },
  { main: 'ChatGPT', similar: 'Gemini' },
  { main: 'Zoom', similar: 'Teams' },
  { main: 'Slack', similar: 'Discord' },
  { main: 'Photoshop', similar: 'GIMP' },
  { main: 'Word', similar: 'Google Docs' },
  { main: 'Excel', similar: 'Google Sheets' },
  { main: 'PowerPoint', similar: 'Keynote' },
  { main: 'Chrome', similar: 'Firefox' },
  { main: 'Safari', similar: 'Edge' },
  { main: 'Android', similar: 'iOS' },
  { main: 'PlayStation', similar: 'Xbox' },
  { main: 'Nintendo', similar: 'Sega' },
  { main: 'Steam', similar: 'Epic Games' },
  { main: 'Clé USB', similar: 'Disque dur' },
  { main: 'Souris', similar: 'Trackpad' },
  { main: 'Clavier', similar: 'Écran tactile' },
  { main: 'Imprimante', similar: 'Scanner' },
  { main: 'Webcam', similar: 'Caméra' },
  { main: 'Casque', similar: 'Écouteurs' },
  { main: 'Enceinte', similar: 'Barre de son' },
  { main: 'Drone', similar: 'Robot' },
  { main: 'GPS', similar: 'Boussole' },
  { main: 'Montre connectée', similar: 'Bracelet fitness' },
  
  // ==================== ÉVÉNEMENTS ====================
  { main: 'Mariage', similar: 'Fiançailles' },
  { main: 'Anniversaire', similar: 'Fête' },
  { main: 'Noël', similar: 'Nouvel An' },
  { main: 'Pâques', similar: 'Carnaval' },
  { main: 'Halloween', similar: 'Toussaint' },
  { main: 'Concert', similar: 'Festival' },
  { main: 'Fête nationale', similar: 'Jour férié' },
  { main: 'Saint-Valentin', similar: 'Fête des amoureux' },
  { main: 'Fête des mères', similar: 'Fête des pères' },
  { main: 'Baptême', similar: 'Communion' },
  { main: 'Enterrement', similar: 'Crémation' },
  { main: 'Remise de diplôme', similar: 'Cérémonie' },
  { main: 'Salon', similar: 'Exposition' },
  { main: 'Conférence', similar: 'Séminaire' },
  { main: 'Marathon', similar: 'Course caritative' },
  { main: 'Manifestation', similar: 'Grève' },
  { main: 'Élection', similar: 'Référendum' },
  { main: 'Inauguration', similar: 'Vernissage' },
  { main: 'Défilé', similar: 'Parade' },
  { main: 'Feu d\'artifice', similar: 'Spectacle' },
  
  // ==================== ABSTRAITS ====================
  { main: 'Amour', similar: 'Amitié' },
  { main: 'Joie', similar: 'Bonheur' },
  { main: 'Colère', similar: 'Frustration' },
  { main: 'Peur', similar: 'Anxiété' },
  { main: 'Rêve', similar: 'Cauchemar' },
  { main: 'Silence', similar: 'Calme' },
  { main: 'Liberté', similar: 'Indépendance' },
  { main: 'Vérité', similar: 'Honnêteté' },
  { main: 'Mensonge', similar: 'Tromperie' },
  { main: 'Courage', similar: 'Bravoure' },
  { main: 'Patience', similar: 'Persévérance' },
  { main: 'Sagesse', similar: 'Intelligence' },
  { main: 'Créativité', similar: 'Imagination' },
  { main: 'Nostalgie', similar: 'Mélancolie' },
  { main: 'Espoir', similar: 'Optimisme' },
  { main: 'Désespoir', similar: 'Pessimisme' },
  { main: 'Fierté', similar: 'Orgueil' },
  { main: 'Humilité', similar: 'Modestie' },
  { main: 'Jalousie', similar: 'Envie' },
  { main: 'Générosité', similar: 'Altruisme' },
  { main: 'Égoïsme', similar: 'Narcissisme' },
  { main: 'Compassion', similar: 'Empathie' },
  { main: 'Respect', similar: 'Considération' },
  { main: 'Confiance', similar: 'Foi' },
  { main: 'Doute', similar: 'Incertitude' },
  { main: 'Mystère', similar: 'Énigme' },
  { main: 'Destin', similar: 'Fatalité' },
  { main: 'Chance', similar: 'Fortune' },
  { main: 'Malchance', similar: 'Poisse' },
  { main: 'Succès', similar: 'Victoire' },
  { main: 'Échec', similar: 'Défaite' },
  
  // ==================== JEUX ====================
  { main: 'Poker', similar: 'Blackjack' },
  { main: 'Échecs', similar: 'Dames' },
  { main: 'Monopoly', similar: 'Cluedo' },
  { main: 'Lego', similar: 'Playmobil' },
  { main: 'Mario', similar: 'Sonic' },
  { main: 'Tetris', similar: 'Puyo Puyo' },
  { main: 'Minecraft', similar: 'Roblox' },
  { main: 'Fortnite', similar: 'PUBG' },
  { main: 'GTA', similar: 'Saints Row' },
  { main: 'FIFA', similar: 'PES' },
  { main: 'Call of Duty', similar: 'Battlefield' },
  { main: 'Zelda', similar: 'Dark Souls' },
  { main: 'Pokémon', similar: 'Digimon' },
  { main: 'Uno', similar: 'Skip-Bo' },
  { main: 'Scrabble', similar: 'Bananagrams' },
  { main: 'Trivial Pursuit', similar: 'Quiz' },
  { main: 'Jenga', similar: 'Mikado' },
  { main: 'Pictionary', similar: 'Dessinez c\'est gagné' },
  { main: 'Time\'s Up', similar: 'Taboo' },
  { main: 'Loup-garou', similar: 'Mafia' },
  { main: 'Puzzle', similar: 'Casse-tête' },
  { main: 'Sudoku', similar: 'Mots croisés' },
  { main: 'Rubik\'s Cube', similar: 'Puzzle 3D' },
  { main: 'Cartes', similar: 'Tarot' },
  { main: 'Dominos', similar: 'Mahjong' },
  { main: 'Go', similar: 'Othello' },
  { main: 'Backgammon', similar: 'Jacquet' },
  { main: 'Puissance 4', similar: 'Morpion' },
  { main: 'Bataille navale', similar: 'Stratego' },
  { main: 'Risk', similar: 'Diplomacy' },
  
  // ==================== FILMS/SÉRIES ====================
  { main: 'Harry Potter', similar: 'Seigneur des Anneaux' },
  { main: 'Star Wars', similar: 'Star Trek' },
  { main: 'Batman', similar: 'Superman' },
  { main: 'Spider-Man', similar: 'Iron Man' },
  { main: 'Titanic', similar: 'Avatar' },
  { main: 'Disney', similar: 'Pixar' },
  { main: 'Marvel', similar: 'DC Comics' },
  { main: 'Matrix', similar: 'Inception' },
  { main: 'Jurassic Park', similar: 'King Kong' },
  { main: 'Indiana Jones', similar: 'Tomb Raider' },
  { main: 'James Bond', similar: 'Mission Impossible' },
  { main: 'Fast and Furious', similar: 'Need for Speed' },
  { main: 'Pirates des Caraïbes', similar: 'Peter Pan' },
  { main: 'Shrek', similar: 'Madagascar' },
  { main: 'Toy Story', similar: 'Monstres et Cie' },
  { main: 'Roi Lion', similar: 'Livre de la Jungle' },
  { main: 'Frozen', similar: 'Raiponce' },
  { main: 'Game of Thrones', similar: 'Vikings' },
  { main: 'Breaking Bad', similar: 'Better Call Saul' },
  { main: 'Friends', similar: 'How I Met Your Mother' },
  { main: 'The Office', similar: 'Parks and Recreation' },
  { main: 'Stranger Things', similar: 'Dark' },
  { main: 'La Casa de Papel', similar: 'Lupin' },
  { main: 'Squid Game', similar: 'Alice in Borderland' },
  { main: 'The Walking Dead', similar: 'Fear the Walking Dead' },
  { main: 'Sherlock', similar: 'Elementary' },
  { main: 'Grey\'s Anatomy', similar: 'Dr House' },
  { main: 'Les Simpsons', similar: 'Family Guy' },
  { main: 'South Park', similar: 'Rick et Morty' },
  { main: 'Naruto', similar: 'One Piece' }
];

/**
 * Sélectionner une paire de mots aléatoire
 */
export function getRandomWordPair() {
  const index = Math.floor(Math.random() * WORD_PAIRS.length);
  return WORD_PAIRS[index];
}

/**
 * Obtenir plusieurs paires aléatoires (sans doublons)
 */
export function getRandomWordPairs(count) {
  const shuffled = [...WORD_PAIRS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
